- name: Lookup OBS credentials
  include: auth.yml

- name: create timestamp
  shell: LC_ALL=en TZ=GMT date +"%a, %d %b %Y %T %z"
  register: sigdate

- name: create signature
  vars:
    EC2_URL: "{{ lookup('env','EC2_URL') | default('https://obs.otc.t-systems.com',true) }}"
    EC2_ACCESS_KEY: "{{ lookup('env','EC2_ACCESS_KEY') }}"
    EC2_SECRET_KEY: "{{ lookup('env','EC2_SECRET_KEY') }}"
  shell: |
    set -o pipefail
    exit_code=0
    echo -en "DELETE\n\n\n\nx-amz-date:{{ sigdate.stdout }}\n/{{ bucket }}/{{ object }}" | openssl sha1 -hmac {{ EC2_SECRET_KEY }} -binary | base64
    exit ${exit_code}
  args:
    warn: no
    executable: /bin/bash
  register: signature

- name: curl request upload data
  vars:
    EC2_URL: "{{ lookup('env','EC2_URL') | default('https://obs.otc.t-systems.com',true) }}"
    EC2_ACCESS_KEY: "{{ lookup('env','EC2_ACCESS_KEY') }}"
    EC2_SECRET_KEY: "{{ lookup('env','EC2_SECRET_KEY') }}"
  command: 'curl -X DELETE -H "Authorization: AWS {{ EC2_ACCESS_KEY }}:{{ signature.stdout }}" -H "x-amz-date: {{ sigdate.stdout }}" {{ EC2_URL }}/{{ bucket }}/{{ object }}'
  register: curlresponse

- debug:
    msg: "{{ curlresponse.stdout_lines }}"
